<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-HHFIH5D1" name="Default test" tests="1" failures="1" timestamp="9 Jun 2020 16:31:27 GMT" time="17.927" errors="0">
  <testcase name="feature" time="17.483" classname="com.verifone.testrunners.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [https://www.linkedin.com/company/verifone/] but found [https://www.linkedin.com/authwall?trk=ripf&amp;amp;trkInfo=AQFc7qqG6zf9FAAAAXKZ7At43HnUPpXuIdz4h6s6xurnYBU-GwUGuTytiw0OG3IaxUrhwig1iksW66MrgIcRuoaeKF3n7guPh7Yp06o0GK4NoEZ39LWHmeDkrjrUKcHs-BAk3EY=&amp;amp;originalReferer=&amp;amp;sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fverifone%2F]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [https://www.linkedin.com/company/verifone/] but found [https://www.linkedin.com/authwall?trk=ripf&trkInfo=AQFc7qqG6zf9FAAAAXKZ7At43HnUPpXuIdz4h6s6xurnYBU-GwUGuTytiw0OG3IaxUrhwig1iksW66MrgIcRuoaeKF3n7guPh7Yp06o0GK4NoEZ39LWHmeDkrjrUKcHs-BAk3EY=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fverifone%2F]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [https://www.linkedin.com/company/verifone/] but found [https://www.linkedin.com/authwall?trk=ripf&trkInfo=AQFc7qqG6zf9FAAAAXKZ7At43HnUPpXuIdz4h6s6xurnYBU-GwUGuTytiw0OG3IaxUrhwig1iksW66MrgIcRuoaeKF3n7guPh7Yp06o0GK4NoEZ39LWHmeDkrjrUKcHs-BAk3EY=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fverifone%2F]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.verifone.stepdefinitions.VerifoneEcommerceStepDefs.user_navigates_to(VerifoneEcommerceStepDefs.java:121)
	at âœ½.And User navigates to "https://www.linkedin.com/company/verifone/"(VerifyEcommercePlatform.feature:16)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
